import("//build/lite/config/component/lite_component.gni")

lite_library("lab03_light_key_lcd") {
    target_type = "static_library"

    sources = [
        "lab03_light_key_lcd.c",
        "src/lcd.c",
        "src/tx_key.c",
        "src/tx_light.c",
    ]

    include_dirs = [
        "include",
        "//device/rockchip/rk2206/adapter/include",
        "//device/rockchip/rk2206/sdk_liteos/include",
    ]
}
