diff --git a/device/rockchip/rk2206/sdk_liteos/Makefile b/device/rockchip/rk2206/sdk_liteos/Makefile
--- a/device/rockchip/rk2206/sdk_liteos/Makefile
+++ b/device/rockchip/rk2206/sdk_liteos/Makefile
@@ -48,1 +48,1 @@
-hardware_LIBS = -lhal_iothardware -lhardware -lshellcmd
+hardware_LIBS = -lhal_iothardware -lhardware -lshellcmd -llab01_lcd
