static_library("lab02_key_lcd_adc_diagnostic") {
    sources = [
        "adc5_key_lcd.c",
        "../../src/lcd.c",
    ]

    include_dirs = [
        "//utils/native/lite/include",
        "//device/lockzhiner/rk2206/adapter/include",
        "../../include",
    ]

    deps = [
        "//device/rockchip/hardware:hardware",
    ]
}
