static_library("button_sniffer") {
    sources = [
        "button_sniffer.c",
        "src/lcd.c",
    ]

    include_dirs = [
        "//utils/native/lite/include",
        "//device/lockzhiner/rk2206/adapter/include",
        "include",
    ]

    deps = [
        "//device/rockchip/hardware:hardware",
    ]
}
